import { describe, expect, it } from "vitest";

import { buildHtml } from "../template";
import { buildPdfView } from "../view";
import { sampleInput, sampleView } from "./fixture";

describe("the rendered document", () => {
  const html = buildHtml(sampleView);

  it("shows the company header and quotation details", () => {
    expect(html).toContain("JUNAIDI AIR TRAVELS");
    expect(html).toContain("HQ-1447-0042");
    expect(html).toContain("Rashid Shahid * 02 PAX");
  });

  /**
   * The nights and the Maktab category both already read on the package title
   * line, so repeating them as their own rows was noise.
   */
  it("keeps the details block to the four facts that are not repeated", () => {
    expect(html).toContain("Quotation ID:");
    expect(html).toContain("Guest Name:");
    expect(html).toContain("Valid Until:");
    expect(html).toContain("Package:");
    expect(html).not.toContain("Total Nights:");
    expect(html).not.toContain("Category:");
    expect(html).not.toContain("Flights:");
  });

  it("states Qurbani in the price includes when it is part of the package", () => {
    expect(html).toContain("Qurbani.");
    expect(buildHtml(buildPdfView({ ...sampleInput, qurbaniIncluded: false }))).not.toContain(
      "Qurbani.",
    );
  });

  it("renders every stay", () => {
    for (const stay of sampleView.stays) {
      expect(html).toContain(stay.accommodation);
      expect(html).toContain(stay.dates);
    }
  });

  it("shows both calendars for a stay", () => {
    expect(html).toContain("07 Zilhaj - 12 Zilhaj");
    expect(html).toContain("(22 May - 27 May 2026)");
  });

  it("shows the price once", () => {
    expect(html.split("PKR 919,000 /-").length - 1).toBe(1);
  });
});

/**
 * The journey heads the document, above the itinerary: the day they leave,
 * the day they are back, and the sectors in between.
 */
describe("travel details", () => {
  it("shows both dates and both sectors above the itinerary", () => {
    const html = buildHtml(sampleView);
    expect(html).toContain("Departing on");
    expect(html).toContain("06 May 2026");
    expect(html).toContain("Returning on");
    expect(html).toContain("04 June 2026");
    expect(html).toContain("Karachi - Jeddah");
    expect(html).toContain("Jeddah - Karachi");
    expect(html).toContain("Air Ticket Included");

    // ...and it comes before the itinerary, not after it.
    expect(html.indexOf("Travel Details")).toBeLessThan(
      html.indexOf("Itinerary &amp; Accommodation Details"),
    );
  });

  it("still dates the journey when the guest books their own ticket", () => {
    const html = buildHtml(
      buildPdfView({
        ...sampleInput,
        travel: {
          included: false,
          departureDate: "06 May 2026",
          returnDate: "04 June 2026",
          note: "Air ticket is not part of this package.",
        },
      }),
    );
    expect(html).toContain("06 May 2026");
    expect(html).toContain("Air Ticket Not Included");
    // Said once, in the note - not repeated inside both cards.
    expect(html).not.toContain('class="travel-sector"');
    expect(html.match(/Air ticket is not part of this package\./g)).toHaveLength(1);
  });

  it("falls back to a dash when the calendar gives no date", () => {
    const html = buildHtml(buildPdfView({ ...sampleInput, travel: { included: true } }));
    expect(html).toContain("Departing on");
    expect(html).toContain("—");
  });
});

describe("the two pages", () => {
  const html = buildHtml(sampleView);

  it("prints exactly two sheets", () => {
    expect(html.match(/class="sheet"/g)).toHaveLength(2);
  });

  it("closes page one with the price and page two with the signatures", () => {
    const secondSheet = html.indexOf('class="sheet"', html.indexOf('class="sheet"') + 1);

    expect(html.indexOf("PKR 919,000 /-")).toBeLessThan(secondSheet);
    expect(html.indexOf("Price Includes:")).toBeGreaterThan(secondSheet);
    expect(html.indexOf("Remarks")).toBeGreaterThan(secondSheet);
    expect(html.indexOf("Guest Signature")).toBeGreaterThan(html.indexOf("Remarks"));
    expect(html).toContain("For Junaidi Air Travels");
  });

  it("footers both pages with the staff member and the software house", () => {
    expect(html.match(/Generated by:/g)).toHaveLength(2);
    expect(html.match(/Bilal Ahmed/g)).toHaveLength(2);
    expect(html.match(/Powered by/g)).toHaveLength(2);
    expect(html.match(/\+92 317 2036604/g)).toHaveLength(2);
    expect(html.match(/Digitli/g)).toHaveLength(2);
    expect(html.match(/www\.digitli\.com/g)).toHaveLength(2);
    expect(html).not.toContain("Kodex");
  });

  it("drops the staff line when nobody is named", () => {
    const html = buildHtml(buildPdfView({ ...sampleInput, generatedBy: "" }));
    expect(html).not.toContain("Generated by:");
    // The software line stays either way.
    expect(html.match(/Powered by/g)).toHaveLength(2);
  });
});

describe("conditional sections", () => {
  it("includes Mina and Arafat services when present", () => {
    const html = buildHtml(sampleView);
    expect(html).toContain("Extra Services in Mina");
    expect(html).toContain("Extra Services in Arafat");
    expect(html).toContain("Mic &amp; Speaker in each tent");
  });

  it("omits the services block entirely when both lists are empty", () => {
    const view = buildPdfView({ ...sampleInput, minaServices: [], arafatServices: [] });
    const html = buildHtml(view);
    expect(html).not.toContain("Extra Services in Mina");
    // The class name lives in the stylesheet either way; assert on the markup.
    expect(html).not.toContain('class="footer-cols services-row"');
  });

  it("shows only the list that has content", () => {
    const view = buildPdfView({ ...sampleInput, arafatServices: [] });
    const html = buildHtml(view);
    expect(html).toContain("Extra Services in Mina");
    expect(html).not.toContain("Extra Services in Arafat");
  });

  /** The box is space to write in, so it is printed whether or not it is used. */
  it("prints the remarks box even when there is nothing in it", () => {
    expect(buildHtml(sampleView)).toContain(
      "Rates are subject to availability at the time of confirmation.",
    );
    const empty = buildHtml(buildPdfView({ ...sampleInput, remarks: "   " }));
    expect(empty).toContain('<div class="remarks-body"></div>');
  });

  it("omits the red note when blank", () => {
    const html = buildHtml(buildPdfView({ ...sampleInput, includesNote: "" }));
    expect(html).not.toContain('class="warning-text"');
    expect(html).not.toContain("NOT Included");
  });
});

describe("the discount can never reach the page", () => {
  it("has no field to carry it", () => {
    // A quotation's internal numbers are simply not part of the view type.
    expect(Object.keys(sampleView)).not.toContain("discount");
    expect(Object.keys(sampleView)).not.toContain("subtotal");
    expect(Object.keys(sampleView)).not.toContain("discountNote");
  });

  it("prints no discount wording and no second figure", () => {
    const html = buildHtml(sampleView);
    expect(html.toLowerCase()).not.toContain("discount");
    expect(html.toLowerCase()).not.toContain("subtotal");
    // The only money on the page is the final price.
    expect(html.match(/PKR [\d,]+/g)).toEqual(["PKR 919,000"]);
  });

  it("survives someone trying to smuggle it through", () => {
    const sneaky = buildPdfView({
      ...sampleInput,
      // @ts-expect-error - proving the extra field is dropped, not copied
      discount: 45_000,
      discountNote: "agreed with the guest",
    });
    const html = buildHtml(sneaky);
    expect(html).not.toContain("45000");
    expect(html).not.toContain("45,000");
    expect(html).not.toContain("agreed with the guest");
  });
});

describe("escaping", () => {
  it("escapes user text rather than letting it become markup", () => {
    const view = buildPdfView({
      ...sampleInput,
      guestName: '<script>alert("x")</script>',
      remarks: "Rate < 100 & rising",
    });
    const html = buildHtml(view);
    expect(html).not.toContain("<script>");
    expect(html).toContain("&lt;script&gt;");
    expect(html).toContain("Rate &lt; 100 &amp; rising");
  });

  it("turns newlines in remarks into line breaks", () => {
    const view = buildPdfView({ ...sampleInput, remarks: "line one\nline two" });
    expect(buildHtml(view)).toContain("line one<br>line two");
  });
});

describe("auto-fit scaling", () => {
  it("adds a zoom rule only when scaled", () => {
    expect(buildHtml(sampleView, 1)).not.toContain("zoom:");
    expect(buildHtml(sampleView, 0.88)).toContain("zoom: 0.88;");
  });

  /**
   * Zoom shrinks what is drawn, so the box being drawn into has to grow by the
   * same factor - otherwise a scaled page would stop short of the paper's
   * bottom edge and the price panel would float in the middle of it.
   */
  it("grows the content box by the same factor it shrinks the content", () => {
    expect(buildHtml(sampleView, 1)).toContain("height: 275.000mm;");
    // 275 / 0.88
    expect(buildHtml(sampleView, 0.88)).toContain("height: 312.500mm;");
  });
});
